# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cbin_alloc <- function(x, n, nbin, min, max) {
    .Call(`_kPPR_cbin_alloc`, x, n, nbin, min, max)
}

bin_wts <- function(x, y, n, nbin, min, max) {
    .Call(`_kPPR_bin_wts`, x, y, n, nbin, min, max)
}

ksum <- function(x, y, x_eval, h, n, n_eval, ord, betas) {
    .Call(`_kPPR_ksum`, x, y, x_eval, h, n, n_eval, ord, betas)
}

dksum <- function(x, y, x_eval, h, n, n_eval, ord, betas) {
    .Call(`_kPPR_dksum`, x, y, x_eval, h, n, n_eval, ord, betas)
}

kndksum <- function(x, y, x_eval, h, n, n_eval, ord, betas) {
    .Call(`_kPPR_kndksum`, x, y, x_eval, h, n, n_eval, ord, betas)
}

kndksum_bin <- function(x, y, x_eval, counts, h, n, n_eval, ord, betas) {
    .Call(`_kPPR_kndksum_bin`, x, y, x_eval, counts, h, n, n_eval, ord, betas)
}

